/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConesRouteImport } from './routes/cones'
import { Route as DrillsRouteImport } from './routes/drills'
import { Route as GamesRouteImport } from './routes/games'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as DrillsIndexRouteImport } from './routes/drills.index'
import { Route as DrillsDrillIdRouteImport } from './routes/drills.$drillId'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as PlansIndexRouteImport } from './routes/plans.index'
import { Route as PlansPlanIdRouteImport } from './routes/plans.$planId'
import { Route as PositionsPositionIdRouteImport } from './routes/positions.$positionId'
import { Route as RosterPlayerIdRouteImport } from './routes/roster.$playerId'
import { Route as RosterCompareRouteImport } from './routes/roster.compare'
import { Route as RosterNewRouteImport } from './routes/roster.new'
import { Route as SessionPlanIdRouteImport } from './routes/session.$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConesRoute = ConesRouteImport.update({
  id: '/cones',
  path: '/cones',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsRoute = DrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsIndexRoute = DrillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrillsRoute,
} as any)
const DrillsDrillIdRoute = DrillsDrillIdRouteImport.update({
  id: '/$drillId',
  path: '/$drillId',
  getParentRoute: () => DrillsRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => GamesRoute,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlansRoute,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => PlansRoute,
} as any)
const PositionsPositionIdRoute = PositionsPositionIdRouteImport.update({
  id: '/$positionId',
  path: '/$positionId',
  getParentRoute: () => PositionsRoute,
} as any)
const RosterPlayerIdRoute = RosterPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => RosterRoute,
} as any)
const RosterCompareRoute = RosterCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => RosterRoute,
} as any)
const RosterNewRoute = RosterNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RosterRoute,
} as any)
const SessionPlanIdRoute = SessionPlanIdRouteImport.update({
  id: '/session/$planId',
  path: '/session/$planId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cones': typeof ConesRoute
  '/drills': typeof DrillsRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/plans': typeof PlansRouteWithChildren
  '/positions': typeof PositionsRouteWithChildren
  '/progress': typeof ProgressRoute
  '/roster': typeof RosterRouteWithChildren
  '/safety': typeof SafetyRoute
  '/drills/$drillId': typeof DrillsDrillIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/positions/$positionId': typeof PositionsPositionIdRoute
  '/roster/$playerId': typeof RosterPlayerIdRoute
  '/roster/compare': typeof RosterCompareRoute
  '/roster/new': typeof RosterNewRoute
  '/session/$planId': typeof SessionPlanIdRoute
  '/drills/': typeof DrillsIndexRoute
  '/plans/': typeof PlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cones': typeof ConesRoute
  '/games': typeof GamesRouteWithChildren
  '/positions': typeof PositionsRouteWithChildren
  '/progress': typeof ProgressRoute
  '/roster': typeof RosterRouteWithChildren
  '/safety': typeof SafetyRoute
  '/drills/$drillId': typeof DrillsDrillIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/positions/$positionId': typeof PositionsPositionIdRoute
  '/roster/$playerId': typeof RosterPlayerIdRoute
  '/roster/compare': typeof RosterCompareRoute
  '/roster/new': typeof RosterNewRoute
  '/session/$planId': typeof SessionPlanIdRoute
  '/drills': typeof DrillsIndexRoute
  '/plans': typeof PlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cones': typeof ConesRoute
  '/drills': typeof DrillsRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/plans': typeof PlansRouteWithChildren
  '/positions': typeof PositionsRouteWithChildren
  '/progress': typeof ProgressRoute
  '/roster': typeof RosterRouteWithChildren
  '/safety': typeof SafetyRoute
  '/drills/$drillId': typeof DrillsDrillIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/positions/$positionId': typeof PositionsPositionIdRoute
  '/roster/$playerId': typeof RosterPlayerIdRoute
  '/roster/compare': typeof RosterCompareRoute
  '/roster/new': typeof RosterNewRoute
  '/session/$planId': typeof SessionPlanIdRoute
  '/drills/': typeof DrillsIndexRoute
  '/plans/': typeof PlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cones'
    | '/drills'
    | '/games'
    | '/plans'
    | '/positions'
    | '/progress'
    | '/roster'
    | '/safety'
    | '/drills/$drillId'
    | '/games/$gameId'
    | '/plans/$planId'
    | '/positions/$positionId'
    | '/roster/$playerId'
    | '/roster/compare'
    | '/roster/new'
    | '/session/$planId'
    | '/drills/'
    | '/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cones'
    | '/games'
    | '/positions'
    | '/progress'
    | '/roster'
    | '/safety'
    | '/drills/$drillId'
    | '/games/$gameId'
    | '/plans/$planId'
    | '/positions/$positionId'
    | '/roster/$playerId'
    | '/roster/compare'
    | '/roster/new'
    | '/session/$planId'
    | '/drills'
    | '/plans'
  id:
    | '__root__'
    | '/'
    | '/cones'
    | '/drills'
    | '/games'
    | '/plans'
    | '/positions'
    | '/progress'
    | '/roster'
    | '/safety'
    | '/drills/$drillId'
    | '/games/$gameId'
    | '/plans/$planId'
    | '/positions/$positionId'
    | '/roster/$playerId'
    | '/roster/compare'
    | '/roster/new'
    | '/session/$planId'
    | '/drills/'
    | '/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConesRoute: typeof ConesRoute
  DrillsRoute: typeof DrillsRouteWithChildren
  GamesRoute: typeof GamesRouteWithChildren
  PlansRoute: typeof PlansRouteWithChildren
  PositionsRoute: typeof PositionsRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  RosterRoute: typeof RosterRouteWithChildren
  SafetyRoute: typeof SafetyRoute
  SessionPlanIdRoute: typeof SessionPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cones': {
      id: '/cones'
      path: '/cones'
      fullPath: '/cones'
      preLoaderRoute: typeof ConesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills': {
      id: '/drills'
      path: '/drills'
      fullPath: '/drills'
      preLoaderRoute: typeof DrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills/': {
      id: '/drills/'
      path: '/'
      fullPath: '/drills/'
      preLoaderRoute: typeof DrillsIndexRouteImport
      parentRoute: typeof DrillsRoute
    }
    '/drills/$drillId': {
      id: '/drills/$drillId'
      path: '/$drillId'
      fullPath: '/drills/$drillId'
      preLoaderRoute: typeof DrillsDrillIdRouteImport
      parentRoute: typeof DrillsRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/plans/': {
      id: '/plans/'
      path: '/'
      fullPath: '/plans/'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof PlansRoute
    }
    '/plans/$planId': {
      id: '/plans/$planId'
      path: '/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof PlansRoute
    }
    '/positions/$positionId': {
      id: '/positions/$positionId'
      path: '/$positionId'
      fullPath: '/positions/$positionId'
      preLoaderRoute: typeof PositionsPositionIdRouteImport
      parentRoute: typeof PositionsRoute
    }
    '/roster/$playerId': {
      id: '/roster/$playerId'
      path: '/$playerId'
      fullPath: '/roster/$playerId'
      preLoaderRoute: typeof RosterPlayerIdRouteImport
      parentRoute: typeof RosterRoute
    }
    '/roster/compare': {
      id: '/roster/compare'
      path: '/compare'
      fullPath: '/roster/compare'
      preLoaderRoute: typeof RosterCompareRouteImport
      parentRoute: typeof RosterRoute
    }
    '/roster/new': {
      id: '/roster/new'
      path: '/new'
      fullPath: '/roster/new'
      preLoaderRoute: typeof RosterNewRouteImport
      parentRoute: typeof RosterRoute
    }
    '/session/$planId': {
      id: '/session/$planId'
      path: '/session/$planId'
      fullPath: '/session/$planId'
      preLoaderRoute: typeof SessionPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DrillsRouteChildren {
  DrillsDrillIdRoute: typeof DrillsDrillIdRoute
  DrillsIndexRoute: typeof DrillsIndexRoute
}

const DrillsRouteChildren: DrillsRouteChildren = {
  DrillsDrillIdRoute: DrillsDrillIdRoute,
  DrillsIndexRoute: DrillsIndexRoute,
}

const DrillsRouteWithChildren =
  DrillsRoute._addFileChildren(DrillsRouteChildren)

interface GamesRouteChildren {
  GamesGameIdRoute: typeof GamesGameIdRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesGameIdRoute: GamesGameIdRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

interface PlansRouteChildren {
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  PlansIndexRoute: typeof PlansIndexRoute
}

const PlansRouteChildren: PlansRouteChildren = {
  PlansPlanIdRoute: PlansPlanIdRoute,
  PlansIndexRoute: PlansIndexRoute,
}

const PlansRouteWithChildren = PlansRoute._addFileChildren(PlansRouteChildren)

interface PositionsRouteChildren {
  PositionsPositionIdRoute: typeof PositionsPositionIdRoute
}

const PositionsRouteChildren: PositionsRouteChildren = {
  PositionsPositionIdRoute: PositionsPositionIdRoute,
}

const PositionsRouteWithChildren = PositionsRoute._addFileChildren(
  PositionsRouteChildren,
)

interface RosterRouteChildren {
  RosterPlayerIdRoute: typeof RosterPlayerIdRoute
  RosterCompareRoute: typeof RosterCompareRoute
  RosterNewRoute: typeof RosterNewRoute
}

const RosterRouteChildren: RosterRouteChildren = {
  RosterPlayerIdRoute: RosterPlayerIdRoute,
  RosterCompareRoute: RosterCompareRoute,
  RosterNewRoute: RosterNewRoute,
}

const RosterRouteWithChildren =
  RosterRoute._addFileChildren(RosterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConesRoute: ConesRoute,
  DrillsRoute: DrillsRouteWithChildren,
  GamesRoute: GamesRouteWithChildren,
  PlansRoute: PlansRouteWithChildren,
  PositionsRoute: PositionsRouteWithChildren,
  ProgressRoute: ProgressRoute,
  RosterRoute: RosterRouteWithChildren,
  SafetyRoute: SafetyRoute,
  SessionPlanIdRoute: SessionPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
